s01/discussion/discussion/urls.py
# This is the default comments
"""
URL configuration for discussion project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin

# from django.urls import path --this is the default import we just added the "include" function
from django.urls import include, path

urlpatterns = [
    # create the a route for the todolist package
    path('todolist/', include('todolist.urls')),

    # default path
    path('admin/', admin.site.urls),
]

s01/discussion/todolist/urls.py
from django.urls import path
from . import views

# You can declare routes by using the path function and having 3 arguments within that function.
# 1st argument - endpoint, 2nd argument - function to be triggered, 3rd argument - label for the route
app_name = 'todolist'
urlpatterns = [
	path('', views.index, name = 'index'),
	
	# User
	# /todolist/register
	path('register', views.register, name="register"),
	# /todolist/change_password
	path('change_password', views.change_password, name="change_password"),
	# /todolist/login
	path('login', views.login_view, name="login"),
	# /todolist/logout
	path('logout', views.logout_view, name="logout"),


	# Task
	# /todolist/<todoitem_id>
	path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	# /todolist/add_task
	path('add_task', views.add_task, name="add_task"),
	# /todolist/todoitem_id/edit
	path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
	# /todolist/todoitem_id/delete
	path('<int:todoitem_id>/delete', views.delete_task, name='delete_task'),


	# Event
	# /todolist/<todoitem_id>
	path('<int:eventitem_id>', views.eventitem, name='viewevent'),
	# /todolist/add_event
	path('add_event', views.add_event, name="add_event"),
	# /todolist/eventitem_id/edit
	path('<int:eventitem_id>/edit_event', views.update_event, name='update_event'),
	# /todolist/eventitem_id/delete
	path('<int:eventitem_id>/delete_event', views.delete_event, name='delete_event'),
]

s01/discussion/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap Link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    
    <title>{% block title %} To Do App {% endblock %}</title>
</head>
<body>

    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}

    <!-- Bootstrap Script -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

s01/discussion/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'todolist:index' %}">To Do App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'todolist:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todolist:add_task' %}">Add Task</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todolist:add_event' %}">Add Event</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todolist:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todolist:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>